# Generated by Django 4.0.3 on 2022-03-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=250)),
                ('acquisition_cost', models.IntegerField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('item_properties', models.TextField(max_length=250)),
                ('listing_platform', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('listing_price', models.IntegerField(max_length=100)),
                ('date_of_sale', models.DateTimeField()),
                ('sale_price', models.IntegerField(max_length=100)),
                ('item_image', models.FileField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='kaspersky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='admin', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=14, null=True)),
                ('emp_code', models.CharField(max_length=50, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position')),
            ],
        ),
        migrations.CreateModel(
            name='Antivirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('directorate', models.CharField(max_length=250)),
                ('comp_serial_no', models.CharField(max_length=250)),
                ('antivirus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.kaspersky')),
            ],
            options={
                'verbose_name': 'antivirus',
                'verbose_name_plural': 'antiviruses',
            },
        ),
    ]
