# Generated by Django 4.0.3 on 2022-03-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antivirus',
            old_name='antivirus_id',
            new_name='kaspersky',
        ),
    ]
