# Generated by Django 4.0.3 on 2022-03-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_antivirus_id_antivirus_kaspersky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antivirus',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department'),
        ),
    ]
