# Generated by Django 2.1.5 on 2021-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210227_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='title',
            field=models.CharField(default='admin', max_length=25),
        ),
    ]
