# Generated by Django 4.0.3 on 2022-03-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210307_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=250)),
                ('acquisition_cost', models.IntegerField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('item_properties', models.TextField(max_length=250)),
                ('listing_platform', models.TextField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('listing_price', models.IntegerField(max_length=100)),
                ('date_of_sale', models.DateTimeField()),
                ('sale_price', models.IntegerField(max_length=100)),
                ('item_image', models.FileField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
