# Generated by Django 4.0.3 on 2022-03-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listing_platform',
            field=models.CharField(max_length=100),
        ),
    ]
