# Generated by Django 4.0.3 on 2022-03-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_item_listing_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
