# Generated by Django 4.0.3 on 2022-03-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antivirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus_id', models.CharField(max_length=250)),
                ('officer_name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('directorate', models.CharField(max_length=250)),
                ('comp_serial_no', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
